### ISSUE TITLE
请问一下这个项目为什么配置了两个端口，好像是有一个是ssl的，但是跳转失败

### ISSUE THREAD

**Issue by mebest100** [qcz-left/springboot-layui-qmplatform#3]
请问一下这个项目为什么配置了两个端口，好像是有一个是ssl的，但是跳转失败。
请问是什么原因呢，谢谢

![image](https://user-images.githubusercontent.com/11530991/135750158-efc654cb-3abe-423b-a65d-0dd871afec6c.png)

**Comment by qcz-left** [comment]
一个是http的，一个是https的

**Comment by qcz-left** [comment]
忘记是哪个版本上出现了这个问题，现在没有这个问题了
