### ISSUE TITLE
发现一个小BUG

### ISSUE THREAD

**Issue by VSCIENCE** [qcz-left/springboot-layui-qmplatform#9]
系统运行状态相关模块，扫描到E盘光盘，这个盘总量为0，
`SystemUtils.getDisk`方法中
`sysFile.setUsage(Arith.mul(Arith.div(used, total, 4), 100));`这里调用div会报错 `/ by zero`
![image](https://user-images.githubusercontent.com/43576587/155719921-ba6c5d3e-98a8-4d74-b2a9-529986fdcd11.png)
我在div方法中加了个判断double类型被除数v2为0直接返回某个值时才可以正常使用，否则无法正常使用系统运行状态模块

**Comment by qcz-left** [comment]
感谢提供支持及修复建议，没考虑到磁盘空间为0的情况，已修复
